### ISSUE TITLE
Fix HTTP -> HTTPS redirect in Traefik

### ISSUE THREAD

**Issue by einari** [dolittle-platform/home#81]
We want to redirect everything from HTTP to HTTPS.
It depends on having #83 fixed

We're expecting the redirect to be permanent (301) - we can live with a 302, but prefer 301.

We need confirmation that the SMS Eagle with Red Cross will work redirecting

- [ ] http://cbs-eagle.dolittle.cloud -> HTTPS 
- [ ] http://cbs-demo-eagle.dolittle.cloud -> HTTPS

The best way to confirm the redirect is to use the `wget`CLI tool - it will show exactly what is going on.

The redirect config in `traefik.toml` file could be something like below:

```toml
 [entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"  
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
```
